name: Go testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Get dependencies
      run: go get -v -t -d -u ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test .
        cd doko
        go test .
        cd ../logic
        go test .
        cd ..
