name: Checking Codestyle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2

    - name: Install Go Linter
      run: |
        go get -u golang.org/x/lint/golint
        echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Lint Action
      uses: wearerequired/lint-action@v1.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        golint: true
        golint_args: ./...
