name: JS testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version:  1.15

    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with: 
        node-version: '15'

    - name: Run JS tests
      run: ./jstest/test.sh

    - name: Install ESLint
      run: npm install eslint

    - name: Lint Actions
      uses: wearerequired/lint-action@v1.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint: true
        eslint_args: static/*.js static/*.mjs

