name: JS testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version:  1.15

    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with: 
        node-version: '15'

    - name: Run JS tests
      run: ./jstest/test.sh

    - name: Install ESLint
      run: npm -g install eslint

    - name: Lint
      run: eslint static/*.js static/*.mjs
