name: Frontend testing via node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version:  1.15
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with: 
        node-version: '15'
    - run: ./jstest/test.sh
